### ISSUE TITLE
Wrong register in threshold

### ISSUE THREAD

**Issue by dahult** [adafruit/micropython-adafruit-tcs34725#2]
In lines 137-138 in the threshold method, it sets max_value to _REGISTER_AILT.  Should max_value be  set  to _REGISTER_AIHT?

**Comment by deshipu** [comment]
Nice catch! Do you want to make a pull request for this?

**Comment by dahult** [comment]
I will be glad to make a pull request to submit the change.  This will be my first change submitted to GitHub so I will need to look at the doc to do it correctly.

**Comment by deshipu** [comment]
Please don't hesitate to ask if you have problems with anything. I will be more than happy to help with this. Thank you very much for taking your time to do this!

**Comment by deshipu** [comment]
Fixed with #3. Thank you very much!
